import { GoogleGenerativeAI } from '@google/generative-ai';

export interface LLMResponse {
  success: boolean;
  code?: string;
  error?: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export class LLMClient {
  private client: GoogleGenerativeAI | null = null;
  private apiKey: string | null = null;

  constructor() {
    this.initializeClient();
  }

  private initializeClient() {
    this.apiKey = import.meta.env.VITE_GEMINI_API_KEY || null;
    if (this.apiKey) {
      this.client = new GoogleGenerativeAI(this.apiKey);
    }
  }

  isConfigured(): boolean {
    return this.client !== null && this.apiKey !== null;
  }

  async convertQlikChunk(qlikCode: string, context?: string): Promise<LLMResponse> {
    if (!this.isConfigured()) {
      return {
        success: false,
        error: 'Google Gemini API key not configured. Please set VITE_GEMINI_API_KEY environment variable.'
      };
    }

    try {
      const model = this.client!.getGenerativeModel({ model: 'gemini-1.5-flash' });

      const prompt = `You are an expert ETL developer specializing in converting Qlik Sense scripts to PySpark code.

Your task is to convert Qlik script chunks to equivalent PySpark DataFrame operations.

Guidelines:
- Convert LOAD statements to PySpark DataFrame operations
- Handle data sources (CSV, Excel, QVD, databases)
- Convert Qlik expressions to PySpark SQL expressions
- Maintain table relationships and dependencies
- Use appropriate PySpark functions and methods
- Include proper error handling
- Add comments explaining the conversion
- Return only the PySpark code, no explanations outside code

Context: ${context || 'General Qlik to PySpark conversion'}

Qlik Script to convert:
${qlikCode}`;

      const result = await model.generateContent(prompt);
      const response = result.response;
      const code = response.text().trim();

      if (!code) {
        return {
          success: false,
          error: 'No code generated by LLM'
        };
      }

      // Gemini doesn't provide detailed token counts in the same way
      // but we can estimate based on response
      const estimatedTokens = Math.ceil(code.length / 4); // rough estimation

      return {
        success: true,
        code,
        usage: {
          promptTokens: Math.ceil(prompt.length / 4),
          completionTokens: estimatedTokens,
          totalTokens: Math.ceil(prompt.length / 4) + estimatedTokens
        }
      };

    } catch (error) {
      console.error('LLM conversion error:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown LLM error'
      };
    }
  }
}

export const llmClient = new LLMClient();
