import Groq from 'groq-sdk';

export interface LLMResponse {
  success: boolean;
  code?: string;
  error?: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

export class LLMClient {
  private client: Groq | null = null;
  private apiKey: string | null = null;

  constructor() {
    this.initializeClient();
  }

  private initializeClient() {
    this.apiKey = import.meta.env.VITE_GROQ_API_KEY || null;
    if (this.apiKey) {
      this.client = new Groq({
        apiKey: this.apiKey,
        dangerouslyAllowBrowser: true
      });
    }
  }

  isConfigured(): boolean {
    return this.client !== null && this.apiKey !== null;
  }

  async convertQlikChunk(qlikCode: string, context?: string): Promise<LLMResponse> {
    console.log('🔵 [Frontend] Starting Groq conversion...');
    console.log(`📊 Code length: ${qlikCode.length} chars`);
    
    if (!this.isConfigured()) {
      return {
        success: false,
        error: 'Groq API key not configured.'
      };
    }

    try {
      console.log('📤 Sending to Groq API...');
      const startTime = Date.now();
      
      const completion = await this.client!.chat.completions.create({
        model: 'llama-3.3-70b-versatile',
        messages: [
          {
            role: 'system',
            content: `You are an expert ETL developer specializing in converting Qlik Sense scripts to PySpark code.

Your task is to convert Qlik script chunks to equivalent PySpark DataFrame operations.

Guidelines:
- Convert LOAD statements to PySpark DataFrame operations
- Handle data sources (CSV, Excel, QVD, databases)
- Convert Qlik expressions to PySpark SQL expressions
- Maintain table relationships and dependencies
- Use appropriate PySpark functions and methods
- Include proper error handling
- Add comments explaining the conversion
- Return only the PySpark code, no explanations outside code

Context: ${context || 'General Qlik to PySpark conversion'}`
          },
          {
            role: 'user',
            content: `Qlik Script to convert:\n${qlikCode}`
          }
        ],
        temperature: 0.1,
        max_tokens: 2000
      });

      const duration = Date.now() - startTime;
      console.log(`⏱️ Groq response in ${duration}ms`);

      const code = completion.choices[0]?.message?.content?.trim();

      if (!code) {
        return {
          success: false,
          error: 'No code generated by Groq'
        };
      }

      console.log('✅ Conversion successful!');
      console.log(`📝 Generated code length: ${code.length} chars`);

      return {
        success: true,
        code,
        usage: {
          promptTokens: completion.usage?.prompt_tokens || 0,
          completionTokens: completion.usage?.completion_tokens || 0,
          totalTokens: completion.usage?.total_tokens || 0
        }
      };

    } catch (error) {
      console.error('❌ [Groq] Conversion failed:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Groq API error'
      };
    }
  }
}

export const llmClient = new LLMClient();
